package Kamarad;


/**
* Kamarad/_AccountImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Friday, December 6, 2013 5:40:56 PM GMT
*/

public abstract class _AccountImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Kamarad.Account, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AccountImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getNumber", new java.lang.Integer (0));
    _methods.put ("setNumber", new java.lang.Integer (1));
    _methods.put ("getBalance", new java.lang.Integer (2));
    _methods.put ("setBalance", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Kamarad/Account/getNumber
       {
         int $result = (int)0;
         $result = this.getNumber ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Kamarad/Account/setNumber
       {
         int number = in.read_long ();
         this.setNumber (number);
         out = $rh.createReply();
         break;
       }

       case 2:  // Kamarad/Account/getBalance
       {
         float $result = (float)0;
         $result = this.getBalance ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // Kamarad/Account/setBalance
       {
         float balance = in.read_float ();
         this.setBalance (balance);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Kamarad/Account:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _AccountImplBase
