package Kamarad;


/**
* Kamarad/_AccountImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Saturday, December 7, 2013 1:32:06 AM GMT
*/

public abstract class _AccountImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Kamarad.Account, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AccountImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getNumber", new java.lang.Integer (0));
    _methods.put ("setNumber", new java.lang.Integer (1));
    _methods.put ("getBalance", new java.lang.Integer (2));
    _methods.put ("setBalance", new java.lang.Integer (3));
    _methods.put ("getKamaradTalkKamarad100", new java.lang.Integer (4));
    _methods.put ("setKamaradTalkKamarad100", new java.lang.Integer (5));
    _methods.put ("getKamaradTalkKamarad500", new java.lang.Integer (6));
    _methods.put ("setKamaradTalkKamarad500", new java.lang.Integer (7));
    _methods.put ("getKamaradTalkEveryone100", new java.lang.Integer (8));
    _methods.put ("setKamaradTalkEveryone100", new java.lang.Integer (9));
    _methods.put ("getKamaradTalkEveryone500", new java.lang.Integer (10));
    _methods.put ("setKamaradTalkEveryone500", new java.lang.Integer (11));
    _methods.put ("getKamaradInternet1GB", new java.lang.Integer (12));
    _methods.put ("setKamaradInternet1GB", new java.lang.Integer (13));
    _methods.put ("getKamardText300", new java.lang.Integer (14));
    _methods.put ("setKamardText300", new java.lang.Integer (15));
    _methods.put ("getKamaradInternational100", new java.lang.Integer (16));
    _methods.put ("setKamaradInternational100", new java.lang.Integer (17));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Kamarad/Account/getNumber
       {
         int $result = (int)0;
         $result = this.getNumber ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Kamarad/Account/setNumber
       {
         int number = in.read_long ();
         this.setNumber (number);
         out = $rh.createReply();
         break;
       }

       case 2:  // Kamarad/Account/getBalance
       {
         float $result = (float)0;
         $result = this.getBalance ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // Kamarad/Account/setBalance
       {
         float balance = in.read_float ();
         this.setBalance (balance);
         out = $rh.createReply();
         break;
       }

       case 4:  // Kamarad/Account/getKamaradTalkKamarad100
       {
         int $result = (int)0;
         $result = this.getKamaradTalkKamarad100 ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // Kamarad/Account/setKamaradTalkKamarad100
       {
         int amount = in.read_long ();
         this.setKamaradTalkKamarad100 (amount);
         out = $rh.createReply();
         break;
       }

       case 6:  // Kamarad/Account/getKamaradTalkKamarad500
       {
         int $result = (int)0;
         $result = this.getKamaradTalkKamarad500 ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 7:  // Kamarad/Account/setKamaradTalkKamarad500
       {
         int amount = in.read_long ();
         this.setKamaradTalkKamarad500 (amount);
         out = $rh.createReply();
         break;
       }

       case 8:  // Kamarad/Account/getKamaradTalkEveryone100
       {
         int $result = (int)0;
         $result = this.getKamaradTalkEveryone100 ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 9:  // Kamarad/Account/setKamaradTalkEveryone100
       {
         int amount = in.read_long ();
         this.setKamaradTalkEveryone100 (amount);
         out = $rh.createReply();
         break;
       }

       case 10:  // Kamarad/Account/getKamaradTalkEveryone500
       {
         int $result = (int)0;
         $result = this.getKamaradTalkEveryone500 ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 11:  // Kamarad/Account/setKamaradTalkEveryone500
       {
         int amount = in.read_long ();
         this.setKamaradTalkEveryone500 (amount);
         out = $rh.createReply();
         break;
       }

       case 12:  // Kamarad/Account/getKamaradInternet1GB
       {
         int $result = (int)0;
         $result = this.getKamaradInternet1GB ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 13:  // Kamarad/Account/setKamaradInternet1GB
       {
         int amount = in.read_long ();
         this.setKamaradInternet1GB (amount);
         out = $rh.createReply();
         break;
       }

       case 14:  // Kamarad/Account/getKamardText300
       {
         int $result = (int)0;
         $result = this.getKamardText300 ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 15:  // Kamarad/Account/setKamardText300
       {
         int amount = in.read_long ();
         this.setKamardText300 (amount);
         out = $rh.createReply();
         break;
       }

       case 16:  // Kamarad/Account/getKamaradInternational100
       {
         int $result = (int)0;
         $result = this.getKamaradInternational100 ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 17:  // Kamarad/Account/setKamaradInternational100
       {
         int amount = in.read_long ();
         this.setKamaradInternational100 (amount);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Kamarad/Account:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _AccountImplBase
