package Kamarad;

/**
* Kamarad/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Saturday, December 7, 2013 1:32:06 AM GMT
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public Kamarad.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (Kamarad.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Kamarad.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Kamarad.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Kamarad.AccountHelper.type ();
  }

}
