package Kamarad;


/**
* Kamarad/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Saturday, December 7, 2013 1:32:06 AM GMT
*/

public interface AccountOperations 
{
  int getNumber ();
  void setNumber (int number);
  float getBalance ();
  void setBalance (float balance);
  int getKamaradTalkKamarad100 ();
  void setKamaradTalkKamarad100 (int amount);
  int getKamaradTalkKamarad500 ();
  void setKamaradTalkKamarad500 (int amount);
  int getKamaradTalkEveryone100 ();
  void setKamaradTalkEveryone100 (int amount);
  int getKamaradTalkEveryone500 ();
  void setKamaradTalkEveryone500 (int amount);
  int getKamaradInternet1GB ();
  void setKamaradInternet1GB (int amount);
  int getKamardText300 ();
  void setKamardText300 (int amount);
  int getKamaradInternational100 ();
  void setKamaradInternational100 (int amount);
} // interface AccountOperations
