package Kamarad;


/**
* Kamarad/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Friday, December 6, 2013 5:40:56 PM GMT
*/

public interface AccountOperations 
{
  int getNumber ();
  void setNumber (int number);
  float getBalance ();
  void setBalance (float balance);
} // interface AccountOperations
