package Kamarad;


/**
* Kamarad/ControlsAccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Friday, December 6, 2013 5:40:56 PM GMT
*/

public interface ControlsAccountOperations 
{
  Kamarad.Account returnAccount (int number);
  Kamarad.Account topUp (int number, float amount);
  Kamarad.Account transfer (int numberOrig, float amount, int numberDest);
} // interface ControlsAccountOperations
