package Kamarad;


/**
* Kamarad/ControlsAccount.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Friday, December 6, 2013 5:40:56 PM GMT
*/

public interface ControlsAccount extends ControlsAccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ControlsAccount
